### ISSUE TITLE
Compatible with Sway?

### ISSUE THREAD

**Issue by hungry-bogart** [catppuccin/hyprlock#10]
I don't know if this only works with Hyperland or not. I'll try it on Sway if that's possible. I don't know what conflicts or disasters might arise.

I also wanted to say that this is a really cool project. My cat approves. *meow*

**Comment by orxngc** [comment]
Afaik, hyprlock styling doesn't have anything to do with which WM you use. Also, I'm fairly sure that hyprlock works on Sway as well.
