### ISSUE TITLE
Placeholder Text Display Issue

### ISSUE THREAD

**Issue by TechLionDev** [catppuccin/hyprlock#3]
It Wont render the place_holder text:
```conf
placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
```

it just shows the value.

**Comment by NikSneMC** [comment]
What color is invalid in rendered value? $textAlpha or $accentAlpha?

**Comment by TechLionDev** [comment]
It Just shows the code as the placeholder, so instead of Logged in as it just shows "<span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>"

Does that make sense?

**Comment by NikSneMC** [comment]
> It Just shows the code as the placeholder, so instead of Logged in as it just shows "󰌾 Logged in as $USER"
> 
> Does that make sense?

I don't think so. What hyprlock version do you use?

**Comment by TechLionDev** [comment]
![image](https://github.com/catppuccin/hyprlock/assets/102739644/f42ffd87-4344-448c-9cf0-9f30df1d0ac9)

**Comment by jaybobsilver** [comment]
I am also facing this problem. Something about the text color variables not parsing correctly within the `<span>` tag. I can get it to work if I reference the color codes directly.

This is the snippet out of my config:

```
placeholder_text = <span foreground="##cad3f5"><i>󰌾 Logged in as </i><span foreground="##b7bdf8">$USER</span></span>

#placeholder_text = <span foreground="##$textAlpha"><i>󰌾 Logged in as </i><span foreground="##$accentAlpha">$USER</span></span>
```

**Comment by NikSneMC** [comment]
Maybe you have wrong colors? Is source on 1st line valid?

**Comment by TechLionDev** [comment]
It is.

**Comment by jaybobsilver** [comment]
> Maybe you have wrong variables? Is source on 1st line valid?

All the other colors pull correctly, and to make sure I set the variable for those colors within the hyprlock.conf file itself. Same issue.

**Comment by TechLionDev** [comment]
![20240401_152254](https://github.com/catppuccin/hyprlock/assets/102739644/b6427f99-f776-45e6-b91e-4fa3034bc2d5)
I Took A Picture with my Phone hopefully it helps

**Comment by NikSneMC** [comment]
> ![20240401_152254](https://private-user-images.githubusercontent.com/102739644/318544184-b6427f99-f776-45e6-b91e-4fa3034bc2d5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5OTk3NjYsIm5iZiI6MTcxMTk5OTQ2NiwicGF0aCI6Ii8xMDI3Mzk2NDQvMzE4NTQ0MTg0LWI2NDI3Zjk5LWY3NzYtNDVlNi1iOTFlLTRmYTMwMzRiYzJkNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxOTI0MjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjM2YWNmNGRmYTY4MGMxMDRjNDUxNzM1M2ViZDg3NjU1MjNhYzlhNjQ4NjFlMTJiYzFiZDFkYTE3MjFkYzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uaPwUHN1wVBE1h4OWs7WkeuAec8zL2Vk7_oFL9ymP6k) I Took A Picture with my Phone hopefully it helps

It helps a lot! $tealAlpha is parsed as $teal + Alpha (IDK why)

**Comment by TechLionDev** [comment]
This Works Except for the Password Dots bieng black:
```conf
source = $HOME/.config/hypr/mocha.conf

$accent = $sapphire
$accent2 = $sapphireAlpha
$text2 = $textAlpha
$text = $text
$font = JetBrainsMono Nerd Font

# GENERAL
general {
    disable_loading_bar = true
    hide_cursor = true
}

# BACKGROUND
background {
    path = screenshot
    blur_size = 5
    blur_passes = 4
    monitor =
    # path = ~/.config/background
    # blur_passes = 0
    color = $base
}

# TIME
label {
    monitor =
    text = cmd[update:30000] echo "$(date +"%R")"
    color = $text
    font_size = 90
    font_family = $font
    position = -30, 0
    halign = right
    valign = top
}

# DATE 
label {
    monitor = 
    text = cmd[update:43200000] echo "$(date +"%A, %d %B %Y")"
    color = $text
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

# USER AVATAR

image {
    monitor = 
    path = ~/.face
    size = 100
    border_color = $accent

    position = 0, 75
    halign = center
    valign = center
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 4
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = $accent
    inner_color = $surface0
    font_color = $text
    fade_on_empty = false
    placeholder_text = <span foreground="##$text2"><i>󰌾 Logged in as </i><span foreground="##$accent2">$USER</span></span>
    hide_input = false
    check_color = $accent
    fail_color = $red
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = $yellow
    position = 0, -35
    halign = center
    valign = center
}
```

**Comment by TechLionDev** [comment]
if i figure out the dots ill PR
