### ISSUE TITLE
Publish cat line as PNG

### ISSUE THREAD

**Issue by Mikilio** [catppuccin/hyprlock#6]
Can you publish a PNG of that horizontal line with the cat, so I can display this over my background? It looks quite nice.

**Comment by rubyowo** [comment]
https://raw.githubusercontent.com/catppuccin/catppuccin/main/assets/footers/gray0_ctp_on_line.svg

Already publishhed, and this is definitely the wrong place for this.

**Comment by NikSneMC** [comment]
> Can you publish a PNG of that horizontal line with the cat, so I can display this over my background? It looks quite nice.

As @rubyowo already said, you can download svg. Then just color it. Or just extarct it from [Catppuccin for Vivaldi](https://github.com/catppuccin/vivaldi)

_I defenetely should add this to the FAQ..._
